# -*- coding: utf-8 -*-
"""Fraud_Flag_trial_by_computation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PdLon0DEYztXOLX1z5iwSLfsSfGE_xyA

# Data import and lib installation
"""

import pandas as pd
import tensorflow as tf
import numpy as no
import matplotlib.pyplot as plt

df = pd.read_csv('bank.csv')

data=df

data['Serial No'] = data['Serial No'].astype('float64')

data['WITHDRAWAL AMT'] = data['WITHDRAWAL AMT'].str.replace(',', '')  # Remove commas
data['WITHDRAWAL AMT'] = data['WITHDRAWAL AMT'].astype('float64')    # Convert to float64
data['WITHDRAWAL AMT'].fillna(0, inplace=True)

data['DEPOSIT AMT'] = data['DEPOSIT AMT'].str.replace(',', '')  # Remove commas
data['DEPOSIT AMT'] = data['DEPOSIT AMT'].astype('float64')    # Convert to float64
data['DEPOSIT AMT'].fillna(0, inplace=True)

data['BALANCE AMT'] = data['BALANCE AMT'].str.replace(',', '')  # Remove commas
data['BALANCE AMT'] = data['BALANCE AMT'].astype('float64')    # Convert to float64
# data['DATE'].fillna(0, inplace=True)
# data['VALUE DATE'].fillna(0, inplace=True)

# df['DATE'] = pd.to_datetime(df['DATE'], errors='coerce')
# df['DATE'] = pd.to_numeric(df['DATE'])
# df['VALUE DATE'] = pd.to_datetime(df['VALUE DATE'], errors='coerce')
# df['VALUE DATE'] = pd.to_numeric(df['VALUE DATE'])

"""#ANOMALY0"""

import pandas as pd

def identify_zero_withdrawal_and_deposit(df):
    # Check if both 'WITHDRAWAL AMT' and 'DEPOSIT AMT' are 0 and create a boolean mask
    mask = (df['WITHDRAWAL AMT'] == 0) & (df['DEPOSIT AMT'] == 0)

    # Create a new column 'Zero Transaction' and set it to True for rows that satisfy the condition
    df['Zero Transaction'] = mask

    # Count the number of True and False values in the 'Zero Transaction' column
    count_true_values = df['Zero Transaction'].sum()
    count_false_values = len(df) - count_true_values

    print("Count of True values in 'Zero Transaction' column:", count_true_values)
    print("Count of False values in 'Zero Transaction' column:", count_false_values)

    # Get the row indices where 'Zero Transaction' column has True values
    true_indices = df[df['Zero Transaction']].index
    print("Row indices with True values in 'Zero Transaction' column:", true_indices)

    # Return the DataFrame with the new column
    return df

# Assuming there are 116202 rows in the DataFrame 'group2', apply the function
result = identify_zero_withdrawal_and_deposit(data)

"""These are the locations of those transactions.

#Now leat's head to another operation

# ANOMALY1
"""

import pandas as pd

def create_calculated_balance_column(df):
    # Create a new column named 'Calculated BALANCE'
    df['Calculated BALANCE'] = df['BALANCE AMT'].copy()

    # Loop through the DataFrame starting from the second row (index 1)
    for i in range(1, len(df)):
        # Calculate the calculated balance for row i
        calculated_balance_i = df.loc[i - 1, 'BALANCE AMT'] - df.loc[i, 'WITHDRAWAL AMT'] + df.loc[i, 'DEPOSIT AMT']

        # Store the calculated balance in the 'Calculated BALANCE' column
        df.loc[i, 'Calculated BALANCE'] = calculated_balance_i

    return df

def find_mismatched_serial_numbers(df):
    # Find mismatched rows by comparing 'BALANCE AMT' with 'Calculated BALANCE'
    mismatched_rows = df[df['BALANCE AMT'] != df['Calculated BALANCE']]

    # Get the serial numbers of the mismatched rows
    mismatched_serial_numbers = mismatched_rows['Serial No'].tolist()

    return mismatched_serial_numbers

# Assuming you have a DataFrame 'group2' with columns 'WITHDRAWAL AMT', 'DEPOSIT AMT', and 'BALANCE AMT'
df = create_calculated_balance_column(data)

# Find mismatched serial numbers
mismatched_serial_numbers = find_mismatched_serial_numbers(data)

# Print the serial numbers of mismatched rows
print("Serial numbers of mismatched rows:")
print(mismatched_serial_numbers)

"""# Redundent UTR"""

import pandas as pd

def count_redundant_values(df, column_name):
    # Drop rows with NaN and 0.0 values in the specified column
    df_without_na_or_zero = df[(df[column_name].notna()) & (df[column_name] != 0.0)]

    # Find duplicate values in the specified column and calculate their count
    redundant_count = df_without_na_or_zero.duplicated(subset=column_name, keep=False).sum()

    return redundant_count

def find_redundant_values(df, column_name):
    # Drop rows with NaN and 0.0 values in the specified column
    df_without_na_or_zero = df[(df[column_name].notna()) & (df[column_name] != 0.0)]

    # Find duplicate values in the specified column
    duplicates = df_without_na_or_zero[df_without_na_or_zero.duplicated(subset=column_name, keep=False)]

    # Get the row indices where duplicate values occur
    redundant_indices = duplicates.index.tolist()

    # Get the redundant values in the 'CHQ.NO./ Ref No.' column
    redundant_values = duplicates[column_name].tolist()

    # Get the serial numbers of redundant cells from the 'Serial No.' column
    serial_numbers = df.loc[redundant_indices, 'Serial No'].tolist()

    return redundant_indices, redundant_values, serial_numbers


# Applying the function to find the row indices, values, and serial numbers of redundant cells in the 'CHQ.NO./ Ref No.' column
redundant_indices, redundant_values, serial_numbers = find_redundant_values(group3, 'CHQ.NO./ Ref No.')

# Count the redundant cells (excluding NaN and 0.0 value cells)
redundant_count = count_redundant_values(data, 'CHQ.NO./ Ref No.')

# Display the row indices, values, and serial numbers where redundant cells occur

print("Values of redundant cells:", redundant_values)
print("Serial numbers of redundant cells:", serial_numbers)

# Display the count of redundant cells
print("Count of redundant cells:", redundant_count)

"""#Missing UTR"""

group4 = data.drop(['DATE','VALUE DATE','WITHDRAWAL AMT','DEPOSIT AMT','BALANCE AMT','Label'],axis = 1)
group4

import pandas as pd

def find_nan_values(df, chq_no_column, serial_no_column):
    # Find rows with NaN values in the specified column
    nan_values = df[df[chq_no_column].isna()]

    # Get the serial numbers corresponding to NaN values
    serial_numbers = nan_values[serial_no_column].tolist()

    # Calculate the total count of NaN values
    total_nan_count = nan_values.shape[0]

    return serial_numbers, total_nan_count

# Applying the function to find the serial numbers and total count of NaN values in the 'CHQ.NO./ Ref No.' column
serial_numbers_nan, total_nan_count = find_nan_values(data, 'CHQ.NO./ Ref No.', 'Serial No')

# Display the serial numbers corresponding to NaN values and the total count of NaN values
print("Serial numbers corresponding to NaN values:", serial_numbers_nan)
print("Total count of NaN values:", total_nan_count)

"""# Transaction id is 0 and is not a settlemnent charge or self deposite

"""

group5 = data.drop(['DATE','VALUE DATE','WITHDRAWAL AMT','DEPOSIT AMT','BALANCE AMT','Label'],axis = 1)
group5

import pandas as pd

def find_zero_values(df, chq_no_column, transaction_detail_column, serial_no_column):
    # Find rows with 0.0 values in the specified column
    zero_values = df[df[chq_no_column] == 0.0]

    # Initialize a list to store the serial numbers of rows where 'Transaction detail' is not specific values
    non_specific_transaction_serial_numbers = []

    for index, row in zero_values.iterrows():
        # Check if the 'Transaction detail' column is not any of the specific values
        if row[transaction_detail_column] not in ['atm settlement', 'settlement charges', 'self deposit']:
            non_specific_transaction_serial_numbers.append(row[serial_no_column])

    return non_specific_transaction_serial_numbers

# Applying the function to find the serial numbers of rows with 0.0 values in the 'CHQ.NO./ Ref No.' column
# and not containing specific values in the 'TRANSACTION DETAILS' column
non_specific_transaction_serial_numbers = find_zero_values(data, 'CHQ.NO./ Ref No.', 'TRANSACTION DETAILS', 'Serial No')

# Display the serial numbers corresponding to 0.0 values in the 'CHQ.NO./ Ref No.' column
# and not containing specific values in the 'TRANSACTION DETAILS' column
print("Serial numbers corresponding to 0.0 values and not containing specific values:", non_specific_transaction_serial_numbers)

# Calculate the count of such values
count_non_specific_transaction = len(non_specific_transaction_serial_numbers)
print("Count of such values:", count_non_specific_transaction)

"""# Missing Date"""

import pandas as pd

def find_nan_values(df, date_column, value_date_column, serial_no_column):
    # Filter the DataFrame to get rows with NaN values in the 'Date' column
    nan_date_rows = df[df[date_column].isna()]

    # Get the serial numbers corresponding to the NaN values in the 'Date' column
    nan_date_serial_numbers = nan_date_rows[serial_no_column].tolist()

    # Get the count of NaN values in the 'Date' column
    count_nan_dates = nan_date_rows.shape[0]

    # Filter the DataFrame to get rows with NaN values in the 'Value Date' column
    nan_value_date_rows = df[df[value_date_column].isna()]

    # Get the serial numbers corresponding to the NaN values in the 'Value Date' column
    nan_value_date_serial_numbers = nan_value_date_rows[serial_no_column].tolist()

    # Get the count of NaN values in the 'Value Date' column
    count_nan_value_date = nan_value_date_rows.shape[0]

    # Check if there are NaN values in both the 'DATE' and 'VALUE DATE' columns
    nan_rows = df[df[date_column].isna() & df[value_date_column].isna()]

    # Get the serial numbers of the NaN rows
    nan_both_columns_serial_nos = nan_rows[serial_no_column].tolist()

    # Get the count of the NaN rows
    nan_both_columns_row_count = len(nan_rows)

    return nan_date_serial_numbers, count_nan_dates, nan_value_date_serial_numbers, count_nan_value_date, nan_both_columns_serial_nos, nan_both_columns_row_count

# Assuming you have a DataFrame 'group6' with columns 'DATE', 'VALUE DATE', and 'Serial No'
nan_date_serial_numbers, count_nan_dates, nan_value_date_serial_numbers, count_nan_value_date, nan_both_columns_serial_nos, nan_both_columns_row_count = find_nan_values(data, 'DATE', 'VALUE DATE', 'Serial No')

# Print the serial numbers corresponding to NaN values in the 'Date' column
print("Serial numbers corresponding to NaN values in 'Date' column:", nan_date_serial_numbers)

# Print the count of NaN values in the 'Date' column
print("Count of NaN values in 'Date' column:", count_nan_dates)

# Print the serial numbers corresponding to NaN values in the 'Value Date' column
print("Serial numbers corresponding to NaN values in 'Value Date' column:", nan_value_date_serial_numbers)

# Print the count of NaN values in the 'Value Date' column
print("Count of NaN values in 'Value Date' column:", count_nan_value_date)

# Print the serial numbers of the NaN rows in both 'Date' and 'Value Date' columns
print("Serial numbers of rows with NaN values in both 'Date' and 'Value Date' columns:", nan_both_columns_serial_nos)

# Print the count of rows with NaN values in both 'Date' and 'Value Date' columns
print("Count of rows with NaN values in both 'Date' and 'Value Date' columns:", nan_both_columns_row_count)

"""# Negative Balance"""

import pandas as pd

def find_negative_balance(df, balance_column, serial_no_column):
    # Filter the DataFrame to get rows with negative values in the 'BALANCE AMT' column
    negative_balance_rows = df[df[balance_column] < 0]

    # Get the serial numbers corresponding to the negative values in the 'BALANCE AMT' column
    negative_balance_serial_numbers = negative_balance_rows[serial_no_column].tolist()

    # Get the count of negative values in the 'BALANCE AMT' column
    count_negative_balance = negative_balance_rows.shape[0]

    return negative_balance_serial_numbers, count_negative_balance
# Applying the function to find the serial numbers corresponding to negative values
# and the count of negative values in the 'BALANCE AMT' column
negative_balance_serial_numbers, count_negative_balance = find_negative_balance(data, 'BALANCE AMT', 'Serial No')

# Display the serial numbers corresponding to negative values in the 'BALANCE AMT' column
print("Serial numbers corresponding to negative values in 'BALANCE AMT':", negative_balance_serial_numbers)

# Display the count of negative values in the 'BALANCE AMT' column
print("Count of negative values in 'BALANCE AMT' column:", count_negative_balance)

# """# Suspecious transaction between two parties forming a pattern"""

# group8=data.drop(['Label'],axis = 1)
# group8

# import pandas as pd

# def list_unique_transaction_details(df, transaction_details_column):
#     # Get all unique values in the specified column
#     unique_values = df[transaction_details_column].unique()

#     return unique_values


# # Applying the function to list all the unique values in the 'TRANSACTION DETAILS' column
# unique_transaction_details = list_unique_transaction_details(group8, 'TRANSACTION DETAILS')

# # Display the unique values in the 'TRANSACTION DETAILS' column
# print("Unique values in 'TRANSACTION DETAILS' column:", unique_transaction_details)

# import pandas as pd

# def get_value_counts_transaction_details(df, transaction_details_column):
#     # Get the value counts of each unique value in the specified column
#     value_counts = df[transaction_details_column].value_counts()

#     return value_counts


# # Applying the function to get the value counts of each unique value in the 'TRANSACTION DETAILS' column
# value_counts_transaction_details = get_value_counts_transaction_details(group8, 'TRANSACTION DETAILS')

# # Display the value counts of each unique value in the 'TRANSACTION DETAILS' column
# print("Value counts of each unique value in 'TRANSACTION DETAILS' column:")
# print(value_counts_transaction_details)

# value_counts_transaction_details

# import pandas as pd

# def sum_transactions_exclude_settlements(df, transaction_details_column, withdrawal_column, deposit_column):
#     # Define the list of excluded terms related to bank settlements and statements
#     excluded_terms = ['bank settlement', 'bank settlemennt', 'bank settlemenr', 'bank settlerment', 'bank statement', 'atm settlement', 'atm settled','bank settled','atm  settlement']

#     # Filter out rows with TRANSACTION DETAILS containing the excluded terms
#     df_filtered = df[~df[transaction_details_column].str.lower().str.contains('|'.join(excluded_terms), na=False)]

#     # Group the filtered DataFrame by the 'TRANSACTION DETAILS' column and sum the 'WITHDRAWAL AMT' and 'DEPOSIT AMT'
#     transaction_sums = df_filtered.groupby(transaction_details_column)[[withdrawal_column, deposit_column]].sum()

#     return transaction_sums


# # Applying the function to sum all the transactions by unique values in the 'TRANSACTION DETAILS' column excluding settlements and statements
# transaction_sums = sum_transactions_exclude_settlements(group8, 'TRANSACTION DETAILS', 'WITHDRAWAL AMT', 'DEPOSIT AMT')

# # Convert the resulting DataFrame 'transaction_sums' to a new DataFrame 'result_df'
# result_df = pd.DataFrame(transaction_sums)

# # Save the new DataFrame 'result_df' to a CSV file
# result_df.to_csv('transaction_sums.csv', index=True)

# # Display the new DataFrame 'result_df'
# print(result_df)

# tf=pd.read_csv('transaction_sums.csv')
# tf

# import pandas as pd
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# def calculate_text_similarity(df, transaction_details_column):
#     # Extract the texts from the 'TRANSACTION DETAILS' column
#     texts = df[transaction_details_column].tolist()

#     # Initialize the CountVectorizer
#     vectorizer = CountVectorizer()

#     # Transform the texts into count vectors
#     count_vectors = vectorizer.fit_transform(texts)

#     # Calculate the cosine similarity matrix
#     similarity_matrix = cosine_similarity(count_vectors)

#     return similarity_matrix


# defs = pd.DataFrame(tf)

# # Applying the function to calculate the similarity matrix for 'TRANSACTION DETAILS' column
# similarity_matrix = calculate_text_similarity(defs, 'TRANSACTION DETAILS')

# # Display the similarity matrix
# print(similarity_matrix)

# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.cluster import AgglomerativeClustering

# def group_similar_texts(df, transaction_details_column):
#     # Extract the texts from the 'TRANSACTION DETAILS' column
#     texts = df[transaction_details_column].tolist()

#     # Initialize the CountVectorizer
#     vectorizer = CountVectorizer()

#     # Transform the texts into count vectors
#     count_vectors = vectorizer.fit_transform(texts)

#     # Calculate the cosine similarity matrix
#     similarity_matrix = cosine_similarity(count_vectors)

#     # Perform hierarchical clustering
#     clustering = AgglomerativeClustering(n_clusters=None, affinity='precomputed', linkage='average', distance_threshold=0.5)
#     clusters = clustering.fit_predict(similarity_matrix)

#     # Add the cluster labels to the DataFrame
#     df['Cluster'] = clusters

#     return df

# # For illustration, let's create a sample DataFrame 'df' with the 'TRANSACTION DETAILS' column
# data = {
#     'TRANSACTION DETAILS': ['Purchase', 'ATM Withdrawal', 'Purchase', 'Bill Payment', 'ATM Withdrawal', 'Bank settlement', 'Bank Settlement']
# }

# df = pd.DataFrame(tf)

# # Applying the function to group similar texts based on 'TRANSACTION DETAILS' column
# grouped_df = group_similar_texts(tf, 'TRANSACTION DETAILS')

# # Display the grouped DataFrame with cluster labels
# print(grouped_df)

"""# Suspecious deposite"""

group9=data.drop(['Label','WITHDRAWAL AMT', 'DATE', 'VALUE DATE','BALANCE AMT'],axis = 1)
group9

def find_cash_deposit_serial_numbers(df, transaction_details_column, serial_no_column):
    # Filter rows where 'TRANSACTION DETAILS' contains "Cash Deposit"
    cash_deposit_rows = df[df[transaction_details_column].str.contains("Cash Deposit", case=False, na=False)]

    # Get the serial numbers from the 'Serial No.' column for the filtered rows
    cash_deposit_serial_numbers = cash_deposit_rows[serial_no_column].tolist()

    # Check if the value in 'BALANCE AMT' is greater than 15000000 for the filtered rows
    large_balance_serial_numbers = cash_deposit_rows[cash_deposit_rows['DEPOSIT AMT'] > 15000000][serial_no_column].tolist()

    # Get the 'BALANCE AMT' for the filtered rows with large balance
    large_balance_amt = cash_deposit_rows[cash_deposit_rows['DEPOSIT AMT'] > 15000000]['DEPOSIT AMT'].tolist()

    return cash_deposit_serial_numbers, large_balance_serial_numbers, large_balance_amt


# Applying the function to find serial numbers of rows with "Cash Deposit" in the 'TRANSACTION DETAILS' column
# and check if 'BALANCE AMT' is greater than 15000000 in those rows
cash_deposit_serial_numbers, large_balance_serial_numbers, large_balance_amt = find_cash_deposit_serial_numbers(data, 'TRANSACTION DETAILS', 'Serial No')

# Display the list of serial numbers corresponding to "Cash Deposit" in the 'TRANSACTION DETAILS' column
print("Serial numbers corresponding to 'Cash Deposit' transactions:", cash_deposit_serial_numbers)

# Display the list of serial numbers where 'BALANCE AMT' is greater than 15000000 for "Cash Deposit" transactions
print("Serial numbers with 'DEPOSIT AMT' > 15000000 for 'Cash Deposit' transactions:", large_balance_serial_numbers)

# Display the 'BALANCE AMT' for the rows where 'BALANCE AMT' is greater than 15000000 for "Cash Deposit" transactions
print("BALANCE AMT for 'Cash Deposit' transactions with 'DEPOSIT' > 15000000:", large_balance_amt)

# """# Display of report data"""

# plt.scatter(redundant_indices, serial_numbers)
# plt.xlabel('Row Indices')
# plt.ylabel('Serial Numbers')
# plt.title('Scatter Plot of Serial Numbers for Redundant Cells')
# plt.show()

# plt.figure(figsize=(10, 6))
# plt.scatter(non_specific_transaction_serial_numbers, [1] * count_non_specific_transaction)
# plt.xlabel('Serial Numbers')
# plt.ylabel('Count')
# plt.title('Count of Non-specific Transactions for Each Serial Number')
# plt.show()

# plt.figure(figsize=(10, 6))
# plt.scatter(nan_serial_numbers, [1] * len(nan_serial_numbers))
# plt.xlabel('Serial Numbers')
# plt.ylabel('Count')
# plt.title('Serial Numbers of Rows with NaN Values in DATE Column')
# plt.show()

# plt.figure(figsize=(10, 6))
# plt.scatter(nan_value_date_serial_numbers, [1] * len(nan_value_date_serial_numbers))
# plt.xlabel('Serial Numbers')
# plt.ylabel('Count')
# plt.title('Serial Numbers of Rows with NaN Values in VALUE DATE Column')
# plt.show()

# plt.figure(figsize=(10, 6))
# plt.scatter(nan_serial_nos, [1] * len(nan_serial_nos))
# plt.xlabel('Serial Numbers')
# plt.ylabel('Count')
# plt.title('Serial Numbers of Rows with NaN Values in both DATE and VALUE DATE Columns')
# plt.show()

# plt.figure(figsize=(10, 6))
# plt.scatter(negative_balance_serial_numbers, [1] * len(negative_balance_serial_numbers))
# plt.xlabel('Serial Numbers')
# plt.ylabel('Count')
# plt.title('Serial Numbers of Rows with Negative Values in BALANCE AMT Column')
# plt.show()

# plt.figure(figsize=(10, 6))
# plt.scatter(serial_numbers_nan, [1] * len(serial_numbers_nan))
# plt.xlabel('Serial Numbers')
# plt.ylabel('Count')
# plt.title('Serial Numbers of Rows with NaN Values in CHQ.NO./ Ref No. Column')
# plt.show()

# # Plot 1: Bar plot showing the serial numbers corresponding to "Cash Deposit" transactions
# plt.figure(figsize=(5, 3))
# plt.scatter(cash_deposit_serial_numbers, [1] * len(cash_deposit_serial_numbers))
# plt.xlabel('Serial Numbers')
# plt.ylabel('Count')
# plt.title('Serial Numbers of "Cash Deposit" Transactions')
# plt.show()

# # Plot 2: Bar plot showing the 'BALANCE AMT' for the rows where 'BALANCE AMT' is greater than 15000000 for "Cash Deposit" transactions
# plt.figure(figsize=(5, 3))
# plt.scatter(large_balance_serial_numbers, large_balance_amt)
# plt.xlabel('Serial Numbers')
# plt.ylabel('BALANCE AMT')
# plt.title('BALANCE AMT for "Cash Deposit" Transactions with DEPOSIT > 15000000')
# plt.show()

"""# COMBINED FUNCTION"""

# data

# import pandas as pd

# def create_calculated_balance_column(df):
#     # Create a new column named 'Calculated BALANCE'
#     data['Calculated BALANCE'] = data['BALANCE AMT'].copy()

#     # Loop through the DataFrame starting from the second row (index 1)
#     for i in range(1, len(df)):
#         # Calculate the calculated balance for row i
#         calculated_balance_i = df.loc[i - 1, 'BALANCE AMT'] - df.loc[i, 'WITHDRAWAL AMT'] + df.loc[i, 'DEPOSIT AMT']

#         # Store the calculated balance in the 'Calculated BALANCE' column
#         df.loc[i, 'Calculated BALANCE'] = calculated_balance_i

#     return df

# def find_mismatched_serial_numbers(df):
#     # Find mismatched rows by comparing 'BALANCE AMT' with 'Calculated BALANCE'
#     mismatched_rows = df[df['BALANCE AMT'] != df['Calculated BALANCE']]

#     # Get the serial numbers of the mismatched rows
#     mismatched_serial_numbers = mismatched_rows['Serial No'].tolist()

#     return mismatched_serial_numbers

# # Assuming you have a DataFrame 'group2' with columns 'WITHDRAWAL AMT', 'DEPOSIT AMT', and 'BALANCE AMT'
# df = create_calculated_balance_column(data)

# # Display the first few rows of the DataFrame
# print(df.head())

# # Find mismatched serial numbers
# mismatched_serial_numbers = find_mismatched_serial_numbers(data)

# # Print the serial numbers of mismatched rows
# print("Serial numbers of mismatched rows:")
# print(mismatched_serial_numbers)

# import pandas as pd

# def identify_zero_withdrawal_and_deposit(df):
#     # Check if both 'WITHDRAWAL AMT' and 'DEPOSIT AMT' are 0 and create a boolean mask
#     mask = (df['WITHDRAWAL AMT'] == 0) & (df['DEPOSIT AMT'] == 0)

#     # Create a new column 'Zero Transaction' and set it to True for rows that satisfy the condition
#     df['Zero Transaction'] = mask

#     # Count the number of True and False values in the 'Zero Transaction' column
#     count_true_values = df['Zero Transaction'].sum()
#     count_false_values = len(df) - count_true_values

#     print("Count of True values in 'Zero Transaction' column:", count_true_values)
#     print("Count of False values in 'Zero Transaction' column:", count_false_values)

#     # Get the row indices where 'Zero Transaction' column has True values
#     true_indices = df[df['Zero Transaction']].index
#     print("Row indices with True values in 'Zero Transaction' column:", true_indices)

#     # Return the DataFrame with the new column
#     return df

# # Assuming there are 116202 rows in the DataFrame 'group2', apply the function
# result = identify_zero_withdrawal_and_deposit(data)

# # Display the result (first few rows for illustration)
# print(result.head())

# import pandas as pd

# def process_data(df):
#     # Create a new column named 'Calculated BALANCE'
#     df['Calculated BALANCE'] = df['BALANCE AMT'].copy()

#     # Loop through the DataFrame starting from the second row (index 1)
#     for i in range(1, len(df)):
#         # Calculate the calculated balance for row i
#         calculated_balance_i = df.loc[i - 1, 'BALANCE AMT'] - df.loc[i, 'WITHDRAWAL AMT'] + df.loc[i, 'DEPOSIT AMT']

#         # Store the calculated balance in the 'Calculated BALANCE' column
#         df.loc[i, 'Calculated BALANCE'] = calculated_balance_i

#     # Find mismatched rows by comparing 'BALANCE AMT' with 'Calculated BALANCE'
#     mismatched_rows = df[df['BALANCE AMT'] != df['Calculated BALANCE']]

#     # Get the serial numbers of the mismatched rows
#     mismatched_serial_numbers = mismatched_rows['Serial No'].tolist()

#     print("Serial numbers of mismatched rows:")
#     print(mismatched_serial_numbers)

#     # Check if both 'WITHDRAWAL AMT' and 'DEPOSIT AMT' are 0 and create a boolean mask
#     mask = (df['WITHDRAWAL AMT'] == 0) & (df['DEPOSIT AMT'] == 0)

#     # Create a new column 'Zero Transaction' and set it to True for rows that satisfy the condition
#     df['Zero Transaction'] = mask

#     # Count the number of True and False values in the 'Zero Transaction' column
#     count_true_values = df['Zero Transaction'].sum()
#     count_false_values = len(df) - count_true_values

#     # Get the row indices where 'Zero Transaction' column has True values
#     true_indices = df[df['Zero Transaction']].index
#     print("Row indices with True values in 'Zero Transaction' column:", true_indices)

#     return df

# # Assuming you have a DataFrame 'data' with columns 'WITHDRAWAL AMT', 'DEPOSIT AMT', and 'BALANCE AMT'
# result = process_data(data)

# import pandas as pd

# def process_data(df, chq_no_column, serial_no_column):
#     # Create a new column named 'Calculated BALANCE'
#     df['Calculated BALANCE'] = df['BALANCE AMT'].copy()

#     # Loop through the DataFrame starting from the second row (index 1)
#     for i in range(1, len(df)):
#         # Calculate the calculated balance for row i
#         calculated_balance_i = df.loc[i - 1, 'BALANCE AMT'] - df.loc[i, 'WITHDRAWAL AMT'] + df.loc[i, 'DEPOSIT AMT']

#         # Store the calculated balance in the 'Calculated BALANCE' column
#         df.loc[i, 'Calculated BALANCE'] = calculated_balance_i

#     # Find mismatched rows by comparing 'BALANCE AMT' with 'Calculated BALANCE'
#     mismatched_rows = df[df['BALANCE AMT'] != df['Calculated BALANCE']]

#     # Get the serial numbers of the mismatched rows
#     mismatched_serial_numbers = mismatched_rows['Serial No'].tolist()

#     print("Serial numbers of mismatched rows:")
#     print(mismatched_serial_numbers)

#     # Check if both 'WITHDRAWAL AMT' and 'DEPOSIT AMT' are 0 and create a boolean mask
#     mask = (df['WITHDRAWAL AMT'] == 0) & (df['DEPOSIT AMT'] == 0)

#     # Create a new column 'Zero Transaction' and set it to True for rows that satisfy the condition
#     df['Zero Transaction'] = mask

#     # Count the number of True and False values in the 'Zero Transaction' column
#     count_true_values = df['Zero Transaction'].sum()
#     count_false_values = len(df) - count_true_values

#     print("Count of True values in 'Zero Transaction' column:", count_true_values)
#     print("Count of False values in 'Zero Transaction' column:", count_false_values)

#     # Get the row indices where 'Zero Transaction' column has True values
#     true_indices = df[df['Zero Transaction']].index
#     print("Row indices with True values in 'Zero Transaction' column:", true_indices)

#     # Find rows with NaN values in the specified column
#     nan_values = df[df[chq_no_column].isna()]

#     # Get the serial numbers corresponding to NaN values
#     serial_numbers_nan = nan_values[serial_no_column].tolist()

#     # Calculate the total count of NaN values
#     total_nan_count = nan_values.shape[0]

#     print("Serial numbers corresponding to Missing UTR values:", serial_numbers_nan)
#     print("Total count of Missing UTR values:", total_nan_count)

#     return df, mismatched_serial_numbers, serial_numbers_nan, total_nan_count

# # Assuming you have a DataFrame 'data' with columns 'WITHDRAWAL AMT', 'DEPOSIT AMT', 'BALANCE AMT', 'CHQ.NO./ Ref No.', and 'Serial No'
# result, mismatched_serial_numbers, serial_numbers_nan, total_nan_count = process_data(data, 'CHQ.NO./ Ref No.', 'Serial No')

# import pandas as pd

# def process_data(df, chq_no_column, serial_no_column, transaction_detail_column):
#     # Create a new column named 'Calculated BALANCE'
#     df['Calculated BALANCE'] = df['BALANCE AMT'].copy()

#     # Loop through the DataFrame starting from the second row (index 1)
#     for i in range(1, len(df)):
#         # Calculate the calculated balance for row i
#         calculated_balance_i = df.loc[i - 1, 'BALANCE AMT'] - df.loc[i, 'WITHDRAWAL AMT'] + df.loc[i, 'DEPOSIT AMT']

#         # Store the calculated balance in the 'Calculated BALANCE' column
#         df.loc[i, 'Calculated BALANCE'] = calculated_balance_i

#     # Find mismatched rows by comparing 'BALANCE AMT' with 'Calculated BALANCE'
#     mismatched_rows = df[df['BALANCE AMT'] != df['Calculated BALANCE']]

#     # Get the serial numbers of the mismatched rows
#     mismatched_serial_numbers = mismatched_rows[serial_no_column].tolist()

#     print("Serial numbers of mismatched rows:")
#     print(mismatched_serial_numbers)

#     # Check if both 'WITHDRAWAL AMT' and 'DEPOSIT AMT' are 0 and create a boolean mask
#     mask = (df['WITHDRAWAL AMT'] == 0) & (df['DEPOSIT AMT'] == 0)

#     # Create a new column 'Zero Transaction' and set it to True for rows that satisfy the condition
#     df['Zero Transaction'] = mask

#     # Count the number of True and False values in the 'Zero Transaction' column
#     count_true_values = df['Zero Transaction'].sum()
#     count_false_values = len(df) - count_true_values

#     # Get the row indices where 'Zero Transaction' column has True values
#     true_indices = df[df['Zero Transaction']].index
#     print("Row indices with True values in 'Zero Transaction' column:", true_indices)

#     # Find rows with NaN values in the specified column
#     nan_values = df[df[chq_no_column].isna()]

#     # Get the serial numbers corresponding to NaN values
#     serial_numbers_nan = nan_values[serial_no_column].tolist()

#     # Calculate the total count of NaN values
#     total_nan_count = nan_values.shape[0]

#     print("Serial numbers corresponding to Missing UTR values:", serial_numbers_nan)
#     print("Total count of Missing UTR values:", total_nan_count)

#     # Find rows with 0.0 values in the specified column
#     zero_values = df[df[chq_no_column] == 0.0]

#     # Initialize a list to store the serial numbers of rows where 'Transaction detail' is not specific values
#     non_specific_transaction_serial_numbers = []

#     for index, row in zero_values.iterrows():
#         # Check if the 'Transaction detail' column is not any of the specific values
#         if row[transaction_detail_column] not in ['atm settlement', 'settlement charges', 'self deposit']:
#             non_specific_transaction_serial_numbers.append(row[serial_no_column])

#     print("Serial numbers corresponding to 0.0 values and not containing specific values:", non_specific_transaction_serial_numbers)

#     # Calculate the count of such values
#     count_non_specific_transaction = len(non_specific_transaction_serial_numbers)
#     print("Count of such values:", count_non_specific_transaction)

#     return df, mismatched_serial_numbers, serial_numbers_nan, total_nan_count, non_specific_transaction_serial_numbers, count_non_specific_transaction

# # Assuming you have a DataFrame 'data' with columns 'WITHDRAWAL AMT', 'DEPOSIT AMT', 'BALANCE AMT', 'CHQ.NO./ Ref No.', 'Serial No', and 'TRANSACTION DETAILS'
# result, mismatched_serial_numbers, serial_numbers_nan, total_nan_count, non_specific_transaction_serial_numbers, count_non_specific_transaction = process_data(data, 'CHQ.NO./ Ref No.', 'Serial No', 'TRANSACTION DETAILS')

# import pandas as pd

# def process_data(df, chq_no_column, serial_no_column, transaction_detail_column, date_column, value_date_column):
#     # Part 1: Calculate Calculated BALANCE, find mismatched rows, and check Zero Transaction
#     df['Calculated BALANCE'] = df['BALANCE AMT'].copy()

#     for i in range(1, len(df)):
#         calculated_balance_i = df.loc[i - 1, 'BALANCE AMT'] - df.loc[i, 'WITHDRAWAL AMT'] + df.loc[i, 'DEPOSIT AMT']
#         df.loc[i, 'Calculated BALANCE'] = calculated_balance_i

#     mismatched_rows = df[df['BALANCE AMT'] != df['Calculated BALANCE']]
#     mismatched_serial_numbers = mismatched_rows[serial_no_column].tolist()

#     mask = (df['WITHDRAWAL AMT'] == 0) & (df['DEPOSIT AMT'] == 0)
#     df['Zero Transaction'] = mask
#     count_true_values = df['Zero Transaction'].sum()
#     count_false_values = len(df) - count_true_values
#     true_indices = df[df['Zero Transaction']].index

#     print("Serial numbers of mismatched rows:")
#     print(mismatched_serial_numbers)
#     print("Row indices with True values in 'Zero Transaction' column:", true_indices)
#     print("Count of True values in 'Zero Transaction' column:", count_true_values)
#     print("Count of False values in 'Zero Transaction' column:", count_false_values)

#     # Part 2: Find NaN values in the specified columns
#     nan_date_rows = df[df[date_column].isna()]
#     nan_value_date_rows = df[df[value_date_column].isna()]

#     nan_date_serial_numbers = nan_date_rows[serial_no_column].tolist()
#     count_nan_dates = nan_date_rows.shape[0]

#     nan_value_date_serial_numbers = nan_value_date_rows[serial_no_column].tolist()
#     count_nan_value_date = nan_value_date_rows.shape[0]

#     nan_both_columns_rows = df[df[date_column].isna() & df[value_date_column].isna()]
#     nan_both_columns_serial_nos = nan_both_columns_rows[serial_no_column].tolist()
#     nan_both_columns_row_count = len(nan_both_columns_rows)

#     print("Serial numbers corresponding to NaN values in 'Date' column:", nan_date_serial_numbers)
#     print("Count of NaN values in 'Date' column:", count_nan_dates)
#     print("Serial numbers corresponding to NaN values in 'Value Date' column:", nan_value_date_serial_numbers)
#     print("Count of NaN values in 'Value Date' column:", count_nan_value_date)
#     print("Serial numbers of rows with NaN values in both 'Date' and 'Value Date' columns:", nan_both_columns_serial_nos)
#     print("Count of rows with NaN values in both 'Date' and 'Value Date' columns:", nan_both_columns_row_count)

#     return df, mismatched_serial_numbers, nan_date_serial_numbers, count_nan_dates, nan_value_date_serial_numbers, count_nan_value_date, nan_both_columns_serial_nos, nan_both_columns_row_count, true_indices, count_true_values, count_false_values

# # Assuming you have a DataFrame 'data' with columns 'WITHDRAWAL AMT', 'DEPOSIT AMT', 'BALANCE AMT', 'CHQ.NO./ Ref No.', 'Serial No', 'TRANSACTION DETAILS', 'DATE', and 'VALUE DATE'
# result, mismatched_serial_numbers, nan_date_serial_numbers, count_nan_dates, nan_value_date_serial_numbers, count_nan_value_date, nan_both_columns_serial_nos, nan_both_columns_row_count, true_indices, count_true_values, count_false_values = process_data(data, 'CHQ.NO./ Ref No.', 'Serial No', 'TRANSACTION DETAILS', 'DATE', 'VALUE DATE')

# import pandas as pd

# def process_data(df, chq_no_column, serial_no_column, transaction_detail_column, date_column=None, value_date_column=None):
#     # Part 1: Calculate Calculated BALANCE, find mismatched rows, and check Zero Transaction
#     df['Calculated BALANCE'] = df['BALANCE AMT'].copy()

#     for i in range(1, len(df)):
#         calculated_balance_i = df.loc[i - 1, 'BALANCE AMT'] - df.loc[i, 'WITHDRAWAL AMT'] + df.loc[i, 'DEPOSIT AMT']
#         df.loc[i, 'Calculated BALANCE'] = calculated_balance_i

#     mismatched_rows = df[df['BALANCE AMT'] != df['Calculated BALANCE']]
#     mismatched_serial_numbers = mismatched_rows[serial_no_column].tolist()

#     print("Serial numbers of mismatched rows:")
#     print(mismatched_serial_numbers)

#     # Check if both 'WITHDRAWAL AMT' and 'DEPOSIT AMT' are 0 and create a boolean mask
#     mask = (df['WITHDRAWAL AMT'] == 0) & (df['DEPOSIT AMT'] == 0)
#     df['Zero Transaction'] = mask

#     count_true_values = df['Zero Transaction'].sum()
#     count_false_values = len(df) - count_true_values
#     true_indices = df[df['Zero Transaction']].index

#     print("Row indices with True values in 'Zero Transaction' column:", true_indices)
#     print("Count of True values in 'Zero Transaction' column:", count_true_values)
#     print("Count of False values in 'Zero Transaction' column:", count_false_values)

#     # Find rows with NaN values in the specified column
#     if date_column is not None:
#         nan_date_rows = df[df[date_column].isna()]
#         nan_date_serial_numbers = nan_date_rows[serial_no_column].tolist()
#         count_nan_dates = nan_date_rows.shape[0]

#         print("Serial numbers corresponding to Missing UTR values:", nan_date_serial_numbers)
#         print("Total count of Missing UTR values:", count_nan_dates)



#     # Find rows with 0.0 values in the specified column
#     zero_values = df[df[chq_no_column] == 0.0]

#     non_specific_transaction_serial_numbers = []

#     for index, row in zero_values.iterrows():
#         if row[transaction_detail_column] not in ['atm settlement', 'settlement charges', 'self deposit']:
#             non_specific_transaction_serial_numbers.append(row[serial_no_column])

#     print("Serial numbers corresponding to 0.0 values in UTR:", non_specific_transaction_serial_numbers)

#     count_non_specific_transaction = len(non_specific_transaction_serial_numbers)
#     print("Count of such values:", count_non_specific_transaction)

#     return df, mismatched_serial_numbers, nan_date_serial_numbers, count_nan_dates, nan_value_date_serial_numbers, count_nan_value_date, non_specific_transaction_serial_numbers, count_non_specific_transaction, true_indices, count_true_values, count_false_values

# def find_negative_balance(df, balance_column, serial_no_column):
#     negative_balance_rows = df[df[balance_column] < 0]
#     negative_balance_serial_numbers = negative_balance_rows[serial_no_column].tolist()
#     count_negative_balance = negative_balance_rows.shape[0]

#     return negative_balance_serial_numbers, count_negative_balance

# # Assuming you have a DataFrame 'data' with columns 'WITHDRAWAL AMT', 'DEPOSIT AMT', 'BALANCE AMT', 'CHQ.NO./ Ref No.', 'Serial No', 'TRANSACTION DETAILS', 'DATE', and 'VALUE DATE'
# result, mismatched_serial_numbers, nan_date_serial_numbers, count_nan_dates, nan_value_date_serial_numbers, count_nan_value_date, non_specific_transaction_serial_numbers, count_non_specific_transaction, true_indices, count_true_values, count_false_values = process_data(data, 'CHQ.NO./ Ref No.', 'Serial No', 'TRANSACTION DETAILS', 'DATE', 'VALUE DATE')

# # Applying the function to find the serial numbers corresponding to negative values
# # and the count of negative values in the 'BALANCE AMT' column
# negative_balance_serial_numbers, count_negative_balance = find_negative_balance(data, 'BALANCE AMT', 'Serial No')

# # Display the serial numbers corresponding to negative values in the 'BALANCE AMT' column
# print("Serial numbers corresponding to negative values in 'BALANCE AMT':", negative_balance_serial_numbers)

# # Display the count of negative values in the 'BALANCE AMT' column
# print("Count of negative values in 'BALANCE AMT' column:", count_negative_balance)

